if(!('remove'in Element.prototype)){Element.prototype.remove=function(){if(this.parentNode){this.parentNode.removeChild(this);}};}
__ez.screxqueue=(function(){var STRIP_COMMENTS=/((\/\/.*$)|(\/\*[\s\S]*?\*\/))/mg;var ARGUMENT_NAMES=/([^\s,]+)/g;function getParamNames(func,name){var fnStr=func.toString().replace(STRIP_COMMENTS,'');var result=fnStr.slice(fnStr.indexOf('(')+1,fnStr.indexOf(')')).match(ARGUMENT_NAMES);if(result===null)
result=[];for(var i=0;i<result.length;i++){if(name.indexOf('jQuery-document-ready')===0&&i===0&&result[i].length===1&&typeof window["jQuery"]!=='undefined'&&(typeof window[result[i]]==='undefined'||typeof window[result[i]].fn==='undefined'||typeof window[result[i]].fn.jquery==='undefined')){result[i]=window["jQuery"];}else if(name.lastIndexOf("window-load-listener",0)===0||name.lastIndexOf("dom-content-loaded-listener",0)===0||name.lastIndexOf("windowOnLoad",0)===0||name.lastIndexOf("jQuery-window-load",0)===0){result[i]=new CustomEvent('load');}else{result[i]=window[result[i]];}}
return result;}
var screxCount=0,incr=0,items=[],seItems=[],screxState='',screxStates=['deferLoad','documentReady','documentReady2','documentReady3','domContentLoaded','windowLoad','windowOnLoad'],IsJqLdBfWnd=false,IsJqLdBfDCL=false,completedScrexStates=[];var obj={func:function(el,name,funcName,parameters,isBlock,blockedBy){var self=this;this.el=el;this.name=name;this.funcName=funcName;this.parameters=parameters===null?null:(parameters instanceof Array)?parameters:[parameters];this.isBlock=isBlock;this.blockedBy=blockedBy;this.isError=false;this.isComplete=false;this.isInitialized=false;this.process=function(){log("... func = "+name);self.isInitialized=true;self.isComplete=true;if(self.funcName!==''&&screxStates.indexOf(self.funcName)===-1){log("... func.apply: "+name);if(typeof self.funcName==='function'){self.funcName.apply(window,getParamNames(self.funcName,self.name));}else{var funcs=self.funcName.split('.');var func=null;if(funcs.length>3){}else if(funcs.length===3){func=window[funcs[0]][funcs[1]][funcs[2]];}else if(funcs.length===2){func=window[funcs[0]][funcs[1]];}else{func=window[self.funcName];}
if(typeof func!=='undefined'&&func!==null){func.apply(window,this.parameters);}}}else if(self.funcName==='windowOnLoad'&&'ezoicSSOnLoad'in window&&window["ezoicSSOnLoad"]!=null){window.ezoicSSOnLoad(getParamNames(self.funcName,self.funcName));}else if(self.funcName==='domContentLoaded'){if(typeof jQuery!="undefined"&&IsJqLdBfDCL==false){jQuery(document).trigger("ready");}
fireEvent('EzoicDOMContentLoaded');}else if(self.funcName==='windowLoad'){fireEvent('Ezoicload');if(typeof jQuery!="undefined"&&IsJqLdBfWnd==false){jQuery(window).trigger("load");}}
if(self.isBlock===true){log("----- F'D: "+self.name);processAllScrex();}else{isScrexDone();}}},file:function(el,name,path,isBlock,blockedBy,async,defer){var self=this;this.el=el;this.name=name;this.path=path;this.async=async;this.defer=defer;this.isBlock=isBlock;this.blockedBy=blockedBy;this.isInitialized=false;this.isError=false;this.isComplete=false;this.process=function(){self.isInitialized=true;log("... file = "+name);var scr=document.createElement('script');scr.src=path;if(self.el.hasAttributes()){var attrs=self.el.attributes;for(var i=attrs.length-1;i>=0;i--){if(['id','class','defer'].indexOf(attrs[i].name)>-1||attrs[i].name.indexOf('data-')===0){scr.setAttribute(attrs[i].name,attrs[i].value);}}}
if(async===true)scr.async=true;else if(defer===true)scr.defer=true;scr.onerror=function(){log("----- ERR'D: "+self.name);self.isError=true;self.isComplete=true;if(self.isBlock===true){processAllScrex();}else{isScrexDone();}};scr.onreadystatechange=scr.onload=function(){var state=scr.readyState;log("----- F'D: "+self.name);if((!state||/loaded|complete/.test(state))){self.isComplete=true;if(self.isBlock===true){processAllScrex()}else{isScrexDone();}}};if(self.el!==null&&typeof self.el.parentNode!=='undefined'&&typeof self.el.nextSibling!=='undefined'){var scrAttr=document.createAttribute("ez-screx");scrAttr.value="true",scr.setAttributeNode(scrAttr);self.el.parentNode.insertBefore(scr,self.el.nextSibling);self.el.parentNode.removeChild(self.el);}else{document.getElementsByTagName('head')[0].appendChild(scr);}}}};function setIsJqLdBfWnd(v){this.IsJqLdBfWnd=v;}
function setIsJqLdBfDCL(v){this.IsJqLdBfDCL=v;}
function fireEvent(eventName){var func=function(){window.dispatchEvent(new CustomEvent(eventName))};if(eventName=="Ezoicload"){if(window['__ez__w_load']!=true&&typeof window["__ez__ael"]=="function"){window["__ez__ael"]("load",func)}else{func();}}else if(eventName=="EzoicDOMContentLoaded"){if(window['__ez__w_dom']!=true&&typeof window["__ez__ael"]=="function"){window["__ez__ael"]("DOMContentLoaded",func)}else{func();}}
log('firing event: '+eventName);}
function addScriptExecutionFile(el,name,path,isBlock,blockedBy,async,defer){var item=new obj.file(el,name,path,isBlock,blockedBy,async,defer);log(name+' ... '+' FILE! SCREX');seItems[name]=item;items[name]=item;}
function addScriptExecutionFunc(el,name,func,parameters,isBlock,blockedBy){if(screxStates.indexOf(name)===-1){name=name+"_"+incr++;}
var item=new obj.func(el,name,func,parameters,isBlock,blockedBy);log(name+' ... '+' FUNCTION! SCREX');seItems[name]=item;items[name]=item;if(completedScrexStates.length>0&&screxStates.indexOf(name)===-1){checkIfBlocked(item,true);}}
function checkIfBlocked(item,justAdded){if(isBlocked(item,justAdded)===true)return;item.process();}
function isBlocked(item,justAdded){if(item.blockedBy instanceof Array){for(var i=0;i<item.blockedBy.length;i++){var block=item.blockedBy[i];if(items.hasOwnProperty(block)===false){log(item.name+" blocked = "+block);return true;}else if(items[block].isComplete===false){log(item.name+" blocked = "+block);return true;}else if(justAdded===true&&screxState.indexOf("documentReady")===0){log(item.name+" move to next ready");var idx=item.blockedBy.indexOf("documentReady");if(idx!==-1){item.blockedBy.splice(idx,1);}
switch(screxState){case 'documentReady':item.blockedBy.push("documentReady2");break;case 'documentReady2':item.blockedBy.push("documentReady3");break;}
return true;}}}
return false;}
function isScrexDone(){for(var i in seItems){if(seItems.hasOwnProperty(i)===false)continue;var item=seItems[i];var itemState='';if(item.blockedBy instanceof Array&&item.blockedBy.length>0&&screxStates.indexOf(item.blockedBy[0])!==-1){itemState=item.blockedBy[0];}
if((item.isComplete===false&&item.isError===false)&&itemState===screxState){return false}}
if(completedScrexStates.indexOf(screxState)===-1){completedScrexStates.push(screxState);}
var oldScrexState=screxState;for(var i=0;i<screxStates.length;i++){if(completedScrexStates.indexOf(screxStates[i])===-1){screxState=screxStates[i];break;}}
if(screxState===oldScrexState){return true;}
var blockedBy=oldScrexState==""?[]:[oldScrexState];__ez.screxqueue.addFunc(null,screxState,screxState,[],true,blockedBy);log("screx done for state: "+(oldScrexState===""?"init":oldScrexState));log("screx state now: "+screxState);processAllScrex();return true;}
function log(msg){var href=window.location.href;var reg=new RegExp('[?&]ezscrexq=([^&#]*)','i');var string=reg.exec(href);var res=string?string[1]:null;if(res==="1")console.debug(msg);}
function processAllScrex(){screxCount++;if(screxCount>200)return;log("let's go screx");if('requestIdleCallback'in window&&false){window.requestIdleCallback(function(a){processSmart(a);});}else{processAllItems(seItems,seItems.length);isScrexDone();}}
function processAllItems(list){for(var i in list){if(list.hasOwnProperty(i)===false)continue;var item=list[i];if(item.isComplete===true||isBlocked(item)||item.isInitialized===true||item.isError===true){if(item.isError===true){log(item.name+': error')}else if(item.isComplete===true){log(item.name+': complete already')}else if(item.isInitialized===true){log(item.name+': initialized already')}}else{item.process();}}}
function processSmart(a){var isDone=false;var tr=a.timeRemaining();if(tr>15){isDone=processItems(seItems,Math.floor(tr/10));}
log("is done "+isDone+" time remaining "+tr+" time "+Date.now());if(isDone==false){window.requestIdleCallback(function(a){processSmart(a);});}else{isScrexDone();}}
function processItems(list,numToDo){var numDone=0;var numLooped=0;var numComplete=0;var numBlocked=0;var numItems=Object.keys(list).length;for(var i in list){numLooped++;if(list.hasOwnProperty(i)===false)continue;var item=list[i];var isBlockedItem=isBlocked(item);if(item.isComplete===true||isBlockedItem||item.isInitialized===true||item.isError===true){if(item.isError===true){log(item.name+': error')
numComplete++;}else if(item.isComplete===true){numComplete++;log(item.name+': complete already')}else if(item.isInitialized===true){log(item.name+': initialized already')}else if(isBlockedItem==true){numBlocked++;}}else{item.process();numDone++;}
log(numItems+" - "+numLooped+" - "+numToDo);if(numDone>=numToDo){if(numItems>numLooped){return false;}else{return true;}}}
log("complete: "+numComplete+" items: "+numItems);if(numComplete>=numItems){return true;}else{if((numComplete+numBlocked)==numItems){isScrexDone();}
return false;}}
function init(){log("Init Screx!");processAllScrex();}
return{addFile:addScriptExecutionFile,addFunc:addScriptExecutionFunc,sjql:setIsJqLdBfWnd,sjsdl:setIsJqLdBfDCL,items:items,init:init};})();window.addEventListener("load",function(){if(typeof jQuery!="undefined"){__ez.screxqueue.sjql(true);}});document.addEventListener("DOMContentLoaded",function(){if(typeof jQuery!="undefined"){__ez.screxqueue.sjsdl(true);}});__ez.script.inline=function(e){var scr=document.createElement("script");if(typeof e.id!=='undefined'&&e.id!==null&&e.id!=="")scr.id=e.id;var screxAttr=document.createAttribute("ez-screx");screxAttr.value="true";scr.setAttributeNode(screxAttr);var txtNode=document.createTextNode(e.innerHTML);scr.appendChild(txtNode);if(typeof e.parentNode!=='undefined'&&typeof e.nextSibling!=='undefined'){e.parentNode.insertBefore(scr,e.nextSibling);e.remove();}else{document.body.appendChild(scr);e.remove();}};